openapi: 3.0.3
info:
  title: Collections Web Application API (OpenAPI 3.0.3)
  description: Here you can find all api methods for interactions with CollectionsWebApp backend
  contact:
    email: rusakova.evg@gmail.com
  version: in developement
tags:
  - name: user
    description: operations about users
paths:
  /user/create:
    post:
      tags:
        - user
      summary: Create new user
      description: To create new user, enter email, password and choose a username
      operationId: createNewUser
      requestBody:
        description: parameters for new user
        content:
          application/json:
            schema:
1              $ref: "#/components/schemas/UserRegistrationRequestDto"
      responses:
        '200':
          description: success!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDataResponseDto"
  /user/{username}:
    get:
      tags:
        - user
      summary: Find user by username
      description: Enter username to find the user
      operationId: getUserById
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDataResponseDto"
        '404':
          description: User not found
components:
  schemas:
    UserRegistrationRequestDto:
      type: object
      properties:
        username:
          type: string
          example: thorn_bjornson
        password:
          type: string
          example: password1234
    UserByUsernameRequestDto:
      type: object
      properties:
        username:
          type: string
          example: thorn_bjornson
    UserDataResponseDto:
      type: object
      properties:
        username:
          type: string
          example: thorn_bjornson
        stashes:
          type: array
          items:
            $ref: "#/components/schemas/StashResponseDto"
    UserEditRequestDto:
      type: object
      properties:
        username:
          type: string
    StashRequestDto:
      type: object
      properties:
        title:
          type: string
          example: Collection of ancient coins
        topic:
          type: string
          example: Coins
        description:
          type: string
          example: Contains all the ancient coins I've found during archeological expeditions!
    StashResponseDto:
      type: object
      properties:
        title:
          type: string
          example: Collection of ancient coins
        topic:
          type: string
          example: Coins
        description:
          type: string
          example: Contains all the ancient coins I've found during archeological expeditions!
        artifacts:
          type: array
          items:
            $ref: "#/components/schemas/ArtifactResponseDto"
    ArtifactRequestDto:
      type: object
      properties:
        title:
          type: string
          example: Ancient Greek coin
    ArtifactResponseDto:
      type: object
      properties:
        title:
          type: string
          example: Ancient Greek coin