openapi: 3.0.3
info:
  title: Collections AUTHENTICATION API (OpenAPI 3.0.3)
  description: Here you can find all api methods for authentication
  contact:
    email: rusakova.evg@gmail.com
  version: in developement
tags:
  - name: auth
    description: operations about auth
paths:
  /auth/registration:
    post:
      tags:
        - auth
      summary: Register new User
      description: To regicter new User, choose a username and make up a password
      operationId: registerNewUser
      requestBody:
        description: parameters for new user
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequestDto"
      responses:
        '200':
          description: Success!
components:
  schemas:
    UserRegistrationRequestDto:
      type: object
      properties:
        username:
          type: string
          example: thorn_bjornson
        password:
          type: string
          example: password1234