openapi: 3.0.3
info:
  title: Collections STASH API (OpenAPI 3.0.3)
  description: Here you can find all api methods for operations about Stashes
  contact:
    email: rusakova.evg@gmail.com
  version: v0
tags:
  - name: stash
    description: operations about Stashes
paths:
  /stash/create:
    post:
      tags:
        - stash
      summary: Create new Stash
      description: To create new Stash, enter its title, topic, description and related User ID
      operationId: createNewStash
      requestBody:
        description: parameters for new Stash
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StashCreateRequestDto"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StashResponseDto"
  /stash/{id}:
    get:
      tags:
        - stash
      summary: Find Stash by id
      description: Enter id to find the Stash
      operationId: findStashById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StashResponseDto"
        '404':
          description: Artifact not found
  /stash/all-stashes/{user_id}:
    get:
      tags:
        - stash
      summary: Find Stash by userID
      description: Enter userID to find all their Stashes
      operationId: findAllByUserId
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllStashesResponseDto"
        '404':
          description: No user with provided ID
  /stash/edit:
    put:
      tags:
        - stash
      summary: Edit existing Stash
      operationId: editStash
      requestBody:
        description: Enter new values to the fields you'd like to change
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StashEditRequestDto"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StashResponseDto"
        '404':
          description: Artifact not found
  /stash/delete/{id}:
    delete:
      tags:
        - stash
      summary: Delete Stash by id
      description: Enter id to delete the Stash
      operationId: deleteStashById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '404':
          description: No Stash with provided ID
components:
  schemas:
    StashCreateRequestDto:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
          example: 13
        title:
          type: string
          example: Collection of ancient coins
        topic:
          type: string
          example: Coins
        description:
          type: string
          example: Contains all the ancient coins I've found during archeological expeditions!
    StashEditRequestDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 5
        user_id:
          type: integer
          format: int64
          example: 13
        title:
          type: string
          example: Collection of ancient coins
        topic:
          type: string
          example: Coins
        description:
          type: string
          example: Contains all the ancient coins I've found during archeological expeditions!
    StashResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 5
        user_id:
          type: integer
          format: int64
          example: 13
        title:
          type: string
          example: Collection of ancient coins
        topic:
          type: string
          example: Coins
        description:
          type: string
          example: Contains all the ancient coins I've found during archeological expeditions!
    AllStashesResponseDto:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/StashResponseDto'