openapi: 3.0.3
info:
  title: Collections USER API (OpenAPI 3.0.3)
  description: Here you can find all api methods for operations about Users
  contact:
    email: rusakova.evg@gmail.com
  version: v0
tags:
  - name: user
    description: operations about users
paths:
  /user/signup:
    post:
      tags:
        - user
      summary: Register new User
      description: To register new User, choose a username and make up a password
      operationId: registerNewUser
      requestBody:
        description: parameters for new user
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequestDto"
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDataResponseDto"
  /user/{username}:
    get:
      tags:
        - user
      summary: Find user by username
      description: Enter username to find the user
      operationId: getUserById
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDataResponseDto"
        '404':
          description: User not found
  /user/delete/{id}:
    delete:
      tags:
        - user
      summary: Delete user by provided ID
      description: Enter ID of the user you want to delete
      operationId: deleteUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully deleted!
        '404':
          description: No user with provided ID
components:
  schemas:
    UserRegistrationRequestDto:
      type: object
      properties:
        username:
          type: string
          example: thorn_bjornson
        password:
          type: string
          example: password1234
    UserByUsernameRequestDto:
      type: object
      properties:
        username:
          type: string
          example: thorn_bjornson
    UserDataResponseDto:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        username:
          type: string
          example: thorn_bjornson
    UserEditRequestDto:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        username:
          type: string